name: bird-sounds
channels:
  - conda-forge
  - defaults
dependencies:
  - flask ==2.1.3
  - flask-bootstrap ==3.3.7.1
  - flask-sqlalchemy ==2.5.1
  - pandas ==1.4.3
  - python ==3.10.5
  - rich ==12.5.1
