name: bird-sounds
channels:
  - conda-forge
  - defaults
dependencies:
  - flask ==2.0.2
  - flask-bootstrap ==3.3.7.1
  - flask-sqlalchemy ==2.5.1
  - pandas ==1.3.4
  - python ==3.9.7
  - rich ==10.13.0
