name: bird-sounds
channels:
  - conda-forge
  - defaults
dependencies:
  - flask ==2.2.2
  - flask-bootstrap ==3.3.7.1
  - flask-sqlalchemy ==2.5.1
  - pydub ==0.25.1
  - python ==3.10.6
  - rich ==12.6.0
